const MODEL_MAP_ID = 2;             // ID de la map EventTools
const MODEL_EVENT_NAME = "Caillou"; // Nom de l'événement modèle
const CLONE_KEY = "pagedown";         // Touche de clonage
const ANIMATION_ID = 121; // ID de l'animation
const SLASH_IMAGE = "WeaponAnimationTransparent"; // image dans img/pictures/
const SLASH_DURATION = 15;   // durée en frames
const SLASH_RADIUS = 40;     // distance du balayage en pixels
const SLASH_SCALE = 0.06;    // échelle du sprite
const SLASH_COOLDOWN = 40;
let slashcooldown = 0;
SOUND_NAME_SLASH = "Slash1";
